import pandas as pd
from src.generative_predictor import GenerativePredictor

def test_generative_predictor():
    """Unit test for the generative model based on VAE."""
    # Simulates historical data
    historical_data = pd.DataFrame({
        "n1": [1, 2, 3, 4, 5],
        "n2": [6, 7, 8, 9, 10],
        "n3": [11, 12, 13, 14, 15],
        "n4": [16, 17, 18, 19, 20],
        "n5": [21, 22, 23, 24, 25],
        "pb": [26, 27, 28, 29, 30]
    })

    # Test the generative predictor
    predictor = GenerativePredictor(historical_data)
    predictor.train()
    predictions = predictor.predict(n_samples=5)

    # Verify that 5 predictions are generated
    assert len(predictions) == 5
    print("Predictions generated by the generative model:", predictions)

if __name__ == "__main__":
    test_generative_predictor()
